Makefile
=> makefile help

templates/account/Makefile.tmpl, templates/component/Makefile.tmpl, templates/global/Makefile.tmpl
=> Sh not compatible with -o pipefail

apply/apply_test.go, config/config.go
This has been useless for awhile.
=> remove env type

.gometalinter.json, apply/apply.go, cmd/apply.go, cmd/util.go, config/config.go
A bunch of small fixes found by running `make lint-slow`.
=> gometalinter pass

templates/repo/scripts/component.mk
Add AUTO_APPROVE variable to pass to `make apply`.
=> Add auto approve option to make apply

templates/repo/scripts/component.mk
Introduced in https://github.com/chanzuckerberg/fogg/pull/181
=> Fix docker interactive flags not getting evaluated properly

templates/global/fogg.tf.tmpl
=> set allowed_account_ids in global

plugins/custom_plugin.go, plugins/custom_plugin_test.go
helm tar comes packaged 1 level deep, use this to unbundle to the correct directory
=> Tar strip components when unpacking

apply/apply.go, cmd/util.go, config/config.go, config/config_test.go, config/v1/config.go, config/v1/config_test.go, config/v1/constants.go, init/init.go, plan/plan.go, plan/plan_test.go, plan/travisci.go, plan/travisci_test.go, setup/setup.go, templates/templates.go
In preparation for config/v2, this is a straightforward refactor of config -> config/v1.
Tested by running apply on a few repos and go zero changes.
=> config -> config/v1

config/v2/validation.go, config/v2/validation_test.go
Consolidates some validation logic
unittests
=> Consolidate some validation logic

.travis.yml
Currently we show duplicated spans, this will fix.
* travis build
* https://ui.honeycomb.io/shared-infra/datasets/buildevents/result/cahEDW17Sqk/trace/9Mpm1LYoQJX
=> fix span names for build

templates/account/fogg.tf.tmpl, testdata/v1_full/terraform/accounts/bar/fogg.tf, testdata/v1_full/terraform/accounts/foo/fogg.tf, testdata/v2_full/terraform/accounts/bar/fogg.tf, testdata/v2_full/terraform/accounts/foo/fogg.tf
Similar to other components, accounts now get a reference to all other account's remote state
unittests + ran it in a couple of repos
=> [feature] Add terraform remote state between accounts

templates/repo/scripts/component.mk, testdata/bless_provider/scripts/component.mk, testdata/okta_provider/scripts/component.mk, testdata/snowflake_provider/scripts/component.mk, testdata/v1_full/scripts/component.mk, testdata/v2_full/scripts/component.mk, testdata/v2_minimal_valid/scripts/component.mk, testdata/v2_no_aws_provider/scripts/component.mk
When docker support was removed, we missed a few things.
* unit tests, applied to shared-infra repo
=> [bug] fix makefiles for post-docker support

templates/repo/scripts/module.mk, testdata/bless_provider/scripts/module.mk, testdata/okta_provider/scripts/module.mk, testdata/snowflake_provider/scripts/module.mk, testdata/v1_full/scripts/module.mk, testdata/v2_full/scripts/module.mk, testdata/v2_minimal_valid/scripts/module.mk, testdata/v2_no_aws_provider/scripts/module.mk
`/bin/bash: c: command not found`
applied + tested
=> [fix] Fix linting in modules

config/v1/config.go
=> [fix] Add more missing yaml tags

migrations/migrations.go
The `force` flag previously prevented users from making changes. So I changed the conditional to enable the flag to make changes. 
Manual testing
=> [fix] Fixed force flag conditional

Makefile, go.mod, go.sum, plugins/custom_plugin.go, plugins/custom_plugin_test.go, setup/setup.go, templates/templates_test.go, util/module_storage.go, util/template_test.go, vendor/github.com/google/btree/.travis.yml, vendor/github.com/google/btree/LICENSE, vendor/github.com/google/btree/README.md, vendor/github.com/google/btree/btree.go, vendor/github.com/google/btree/btree_mem.go, vendor/github.com/peterbourgon/diskv/LICENSE, vendor/github.com/peterbourgon/diskv/README.md, vendor/github.com/peterbourgon/diskv/compression.go, vendor/github.com/peterbourgon/diskv/diskv.go, vendor/github.com/peterbourgon/diskv/index.go, vendor/modules.txt
This will cache `fogg setup` -- custom plugins and providers to the fogg cache (currently at `~/.fogg/cache/custom_plugins`)
unittests
=> [feature] Cache fogg setup -- custom plugins and providers

plan/plan.go, plan/plan_test.go, testdata/v2_no_aws_provider/terraform/accounts/bar/fogg.tf, testdata/v2_no_aws_provider/terraform/accounts/foo/fogg.tf
=> [fix] Enable fogg.tf remote state data source for accounts without an aws provider

cmd/exp/aws_config.go
=> [fix] aws_config Null pointer when account with no aws provider

exp/examine/examine.go
Cleaning this up a bit
unittests
=> [fix] some syntax and potential bugs

Makefile
This is a small step towards having generic Makefiles for our go projects.
=> use `go list` to get current package name

templates/repo/Makefile.tmpl, templates/travis-ci/.travis.yml.tmpl, testdata/bless_provider/Makefile, testdata/github_provider/Makefile, testdata/okta_provider/Makefile, testdata/snowflake_provider/Makefile, testdata/v1_full/.travis.yml, testdata/v1_full/Makefile, testdata/v2_full/Makefile, testdata/v2_minimal_valid/Makefile, testdata/v2_no_aws_provider/Makefile, testdata/version_detection/Makefile
Fixes issues with git status --porcelain check.
=> make setup instead of inline download.sh in .travis.yml

templates/repo/Makefile.tmpl, testdata/bless_provider/Makefile, testdata/github_provider/Makefile, testdata/okta_provider/Makefile, testdata/snowflake_provider/Makefile, testdata/v1_full/Makefile, testdata/v2_full/Makefile, testdata/v2_minimal_valid/Makefile, testdata/v2_no_aws_provider/Makefile
* did a test run on 1 repo internally
=> [fix] syntax for version to download

templates/repo/scripts/common.mk, testdata/bless_provider/scripts/common.mk, testdata/github_provider/scripts/common.mk, testdata/okta_provider/scripts/common.mk, testdata/snowflake_provider/scripts/common.mk, testdata/v1_full/scripts/common.mk, testdata/v2_full/scripts/common.mk, testdata/v2_minimal_valid/scripts/common.mk, testdata/v2_no_aws_provider/scripts/common.mk
See https://github.com/chanzuckerberg/tfenv/pull/1 for more context
* unit test
* did a pre-release build and ran it through one of our internal repos
=> [fix] switch to our fork of tfenv

Makefile
=> [build] a few minor makefile improvements

cmd/root.go
=> [fix] only stop cpu profile if we started it

templates/common/heroku_provider.tmpl, testdata/v2_full_yaml/terraform/envs/prod/hero/fogg.tf
heroku provider was missing a closing brace
=> [fix] Add closing brace to heroku provider configuration

.golangci.yml, config/config_test.go, config/v2/validation.go, plugins/custom_plugin_test.go
* add golangci-lint config file which ignores exp directories
* address all current lint errors
* CI
=> lint cleanup

templates/repo/scripts/component.mk, testdata/bless_provider_yaml/scripts/component.mk, testdata/circleci/scripts/component.mk, testdata/component_kind/scripts/component.mk, testdata/github_actions/scripts/component.mk, testdata/github_provider_yaml/scripts/component.mk, testdata/okta_provider_yaml/scripts/component.mk, testdata/snowflake_provider_yaml/scripts/component.mk, testdata/tfe_provider_yaml/scripts/component.mk, testdata/v2_full_yaml/scripts/component.mk, testdata/v2_minimal_valid_yaml/scripts/component.mk, testdata/v2_no_aws_provider_yaml/scripts/component.mk
The terraform remote backend does not support saving a plan file
locally (I can't find docs for this, but that's what the CLI tells me). This
means our check-plan implementation cannot save it for analysis.
With this PR we turn off locally saving a plan file when backend_kind =
remote.
* CI
* tested on 2 interal repos - one that is all remote backend and one that is all s3 backend
* Fixes #464
=> [fix] skip saving planfiles with backend=remote

plan/plan.go, testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf
=> [fix] use role arn with additional regions

templates/repo/scripts/common.mk, testdata/bless_provider_yaml/scripts/common.mk, testdata/circleci/scripts/common.mk, testdata/github_actions/scripts/common.mk, testdata/github_provider_yaml/scripts/common.mk, testdata/okta_provider_yaml/scripts/common.mk, testdata/snowflake_provider_yaml/scripts/common.mk, testdata/tfe_provider_yaml/scripts/common.mk, testdata/v2_full_yaml/scripts/common.mk, testdata/v2_minimal_valid_yaml/scripts/common.mk, testdata/v2_no_aws_provider_yaml/scripts/common.mk
Setting this makes the go sdk behave the way one expects by reading the
aws config.
* CI
* https://docs.aws.amazon.com/sdk-for-go/api/aws/session/
=> [fix] set AWS_SDK_LOAD_CONFIG=1

templates/account/fogg.tf.tmpl, testdata/bless_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/github_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/okta_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/snowflake_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/tfe_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf, testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
Add a `account` variable to account components which includes the name
of the account, as defined by fogg.yml.
* CI
=> [feature] add account name variable

templates/account/fogg.tf.tmpl, testdata/bless_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/github_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/okta_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/snowflake_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/tfe_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf, testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
=> [fix] bug with unquoted account

docs/_config.yml
Config setting that may fix GH pages
Reference thanks to @nacin - https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
=> Set base url for jekyll.

docs/guide/calling_modules.md
Makes examples in the docs more consistent
=> [fix] fix docs consistency

README.md, templates/repo/Makefile.tmpl, testdata/bless_provider_yaml/Makefile, testdata/circleci/Makefile, testdata/github_actions/Makefile, testdata/github_provider_yaml/Makefile, testdata/okta_provider_yaml/Makefile, testdata/snowflake_provider_yaml/Makefile, testdata/tfe_provider_yaml/Makefile, testdata/v2_full_yaml/Makefile, testdata/v2_minimal_valid_yaml/Makefile, testdata/v2_no_aws_provider_yaml/Makefile
Rather than install from master (which is moving to main), install from
the version in question.
* unit tests
=> install fogg from tagged release

plan/plan.go
=> [fix] plan yaml for circleci and github actions

templates/common/common_providers.tmpl, testdata/bless_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/bless_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/bless_provider_yaml/terraform/global/fogg.tf, testdata/circleci/terraform/global/fogg.tf, testdata/github_actions/terraform/global/fogg.tf, testdata/github_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/github_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/github_provider_yaml/terraform/global/fogg.tf, testdata/okta_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/okta_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/okta_provider_yaml/terraform/global/fogg.tf, testdata/snowflake_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/snowflake_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/snowflake_provider_yaml/terraform/global/fogg.tf, testdata/tfe_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/tfe_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/tfe_provider_yaml/terraform/global/fogg.tf, testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf, testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf, testdata/v2_full_yaml/terraform/envs/prod/datadog/fogg.tf, testdata/v2_full_yaml/terraform/envs/prod/hero/fogg.tf, testdata/v2_full_yaml/terraform/envs/prod/vpc/fogg.tf, testdata/v2_full_yaml/terraform/envs/staging/comp1/fogg.tf, testdata/v2_full_yaml/terraform/envs/staging/comp2/fogg.tf, testdata/v2_full_yaml/terraform/envs/staging/vpc/fogg.tf, testdata/v2_full_yaml/terraform/global/fogg.tf, testdata/v2_minimal_valid_yaml/terraform/global/fogg.tf, testdata/v2_no_aws_provider_yaml/terraform/envs/staging/vpc/fogg.tf, testdata/v2_no_aws_provider_yaml/terraform/global/fogg.tf
We hard-code the versions of all these "utility" providers, since users
usually don't bother to specify their versions. Time for a version
upgrade.
* testing manually
=> [breaking] update hardcoded providers

.github/workflows/build.yml
This formatting is technically invalid, I am surprised that it was working.
* CI
=> [build] fix yaml format for build action

plan/plan.go, testdata/v2_full_yaml/terraform/envs/prod/datadog/fogg.tf
Was using the wrong getter for resolving account dependencies in env
components. Really need to refact the plannig code to be more DRY.
* updated golden file tests
* tested with idseq-infra
=> [fix] issue with fetching wrong depends_on

config/config.go, config/v2/config.go, config/v2/validation.go, docs/getting-started/tutorial.md
We long-ago removed this functionality, now remove it from the config
file.
=> remove long-deprecated docker config

README.md, docs/FAQ.md, docs/design.md, docs/getting-started/index.md, docs/getting-started/installation.md, docs/getting-started/tutorial.md, docs/guide/calling_modules.md, docs/guide/directory_structure.md, docs/guide/using_remote_state.md, docs/index.md, docs/reference/cli/apply.md, docs/reference/cli/index.md, docs/reference/cli/init.md, docs/reference/cli/setup.md, docs/reference/config_file.md, docs/reference/index.md, docs/reference/make_targets/apply.md, docs/reference/make_targets/index.md, docs/reference/make_targets/plan.md, docs/reference/make_targets/run.md, docs/reference/make_targets/setup.md
Fix warnings raised by [markdownlint](https://github.com/igorshubovych/markdownlint-cli)
=> markdownlint pass on docs

config/v2/config.go, config/v2/resolvers.go, plan/plan.go, plan/plan_test.go, testdata/tfe_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/tfe_provider_yaml/terraform/global/fogg.tf, testdata/v2_full_yaml/fogg.yml, testdata/v2_full_yaml/terraform/envs/prod/hero/fogg.tf, testdata/v2_full_yaml/terraform/envs/prod/sentry/fogg.tf
Support just for required_versions for now.
* CI
* https://registry.terraform.io/providers/grafana/grafana/latest
=> [feature] support for grafana provider versions

config/v2/config.go, config/v2/resolvers.go, plan/plan.go
This will allow configuring databricks as a required provider in terraform 0.13+
* CI
=> [feature] basic databricks provider support

templates/repo/.gitignore, testdata/bless_provider_yaml/.gitignore, testdata/circleci/.gitignore, testdata/github_actions/.gitignore, testdata/github_provider_yaml/.gitignore, testdata/okta_provider_yaml/.gitignore, testdata/snowflake_provider_yaml/.gitignore, testdata/tfe_provider_yaml/.gitignore, testdata/v2_full_yaml/.gitignore, testdata/v2_minimal_valid_yaml/.gitignore, testdata/v2_no_aws_provider_yaml/.gitignore
=> Gitignore .metals directory

templates/templates/circleci/.circleci/config.yml.tmpl, testdata/circleci/.circleci/config.yml
Installing terraform-docs into circle ci tmpl
referencing this change https://github.com/chanzuckerberg/fogg/blob/main/templates/templates/.github/workflows/fogg_ci.yml.tmpl#L29-L37
=> feat: Add tf doc plugin to circle ci template

.github/workflows/release.yml, .goreleaser.yml, Makefile, codecov.yml
=> feat: Automatic release process

.github/workflows/build.yml, .github/workflows/conventional_commits_title.yml
Removing codecov from this repo
=> feat: Remove codecov from build and create conventional commits workflow

docs/FAQ.md
Dummy PR to trigger release for https://github.com/chanzuckerberg/fogg/pull/674
unittests
=> chore: trigger release

config/v2/resolvers.go, config/v2/validation.go, plan/plan.go, templates/templates/component/terraform/fogg.tf.tmpl
This PR updates fogg so that it doesn't require a global or common backend component. This helps for when we have TFE repos that manage many TFE organizations.
=> feat: no longer require root global backend

.github/workflows/release.yml
This PR fixes the pin on release please. New versions make this action unstable.
=> fix: release please pin

cmd/init.go
=> feat: CCIE-487 dont require bucket or profile

apply/apply.go, apply/apply_test.go
If there exists a locals.tf.json file in the fogg project, on apply it will get updated based on any new envs/accounts or any deleted envs/accounts. For accounts or envs that are already there, it will leave them alone.
=> feat: update locals.tf.json on apply

config/v2/config.go, config/v2/resolvers.go, plan/plan.go
Adding new provider (`opsgenie/opsgenie`) to fogg
=> feat: Add OpsGenie to fogg

apply/apply.go
This PR fixes a bug where the struct to decode locals.tf.json was incomplete.
=> fix: update locals struct to decode

plan/plan.go, testdata/auth0_provider_yaml/terraform/accounts/foo/fogg.tf, testdata/auth0_provider_yaml/terraform/envs/bar/bam/fogg.tf, testdata/auth0_provider_yaml/terraform/global/fogg.tf
This PR updates the auth0 provider name since it has changed recently.
=> fix: update the auth0 provider name

templates/templates/repo/scripts/component.mk, templates/templates/repo/scripts/module.mk, testdata/auth0_provider_yaml/scripts/component.mk, testdata/auth0_provider_yaml/scripts/module.mk, testdata/bless_provider_yaml/scripts/component.mk, testdata/bless_provider_yaml/scripts/module.mk, testdata/circleci/scripts/component.mk, testdata/circleci/scripts/module.mk, testdata/github_actions/scripts/component.mk, testdata/github_actions/scripts/module.mk, testdata/github_provider_yaml/scripts/component.mk, testdata/github_provider_yaml/scripts/module.mk, testdata/okta_provider_yaml/scripts/component.mk, testdata/okta_provider_yaml/scripts/module.mk, testdata/remote_backend_yaml/scripts/component.mk, testdata/remote_backend_yaml/scripts/module.mk, testdata/snowflake_provider_yaml/scripts/component.mk, testdata/snowflake_provider_yaml/scripts/module.mk, testdata/tfe_config/scripts/component.mk, testdata/tfe_config/scripts/module.mk, testdata/tfe_provider_yaml/scripts/component.mk, testdata/tfe_provider_yaml/scripts/module.mk, testdata/v2_full_yaml/scripts/component.mk, testdata/v2_full_yaml/scripts/module.mk, testdata/v2_minimal_valid_yaml/scripts/component.mk, testdata/v2_minimal_valid_yaml/scripts/module.mk, testdata/v2_no_aws_provider_yaml/scripts/component.mk, testdata/v2_no_aws_provider_yaml/scripts/module.mk
=> feat: Add terraform validate support

config/config.go, init/init.go
Upgrades the default TF version and default AWS Provider version to the latest available
=> feat: upgrade default versions

.github/workflows/build.yml
=> chore: update CI

config/v2/config.go, plan/plan.go
Adding a pointer to this values preserves the original variables value when encoded or decoded by yaml.
https://go.dev/play/p/ZFiwObQvbz3
=> fix: to properly encode and decode yaml while preserving variables

download.sh
=> fix: allow for linux/amr64 platform

config/v2/config.go, testdata/component_kind/fogg.yml
=> feat: Add support for an unstructured component templates

README.md
=> fix: version bump re-release

templates/templates/module-invocation/main.tf.tmpl, testdata/v2_full_yaml/fogg.yml, testdata/v2_full_yaml/terraform/envs/prod/vpc/main.tf
This PR fixes a bug where a new line was not set with multiple provider aliases.
=> fix: newline with multiple provider aliases

.github/workflows/build.yml
https://czi.atlassian.net/browse/CCIE-3911
=> chore: remove deprecated tags

.github/workflows/build.yml, .github/workflows/dependabot_automerge.yml, .github/workflows/release.yml, templates/templates/.github/workflows/fogg_ci.yml.tmpl, testdata/github_actions/.github/workflows/fogg_ci.yml, testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
This is an AI generated PR.
Execution time: 137188 ms
Cost: $0.32
=> chore: CCIE-4313 replace tibdex/github-app-token

.github/workflows/build.yml, .github/workflows/dependabot_automerge.yml, .github/workflows/release.yml, templates/templates/.github/workflows/fogg_ci.yml.tmpl, testdata/github_actions/.github/workflows/fogg_ci.yml, testdata/github_actions/fogg.yml, testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
Updates token generation step so the token generated has access to all repos that the github app has access to
=> fix: make token work for all repos

.github/workflows/build.yml, .github/workflows/dependabot_automerge.yml, .github/workflows/release.yml, templates/templates/.github/workflows/fogg_ci.yml.tmpl, testdata/github_actions/.github/workflows/fogg_ci.yml, testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
This is an AI generated PR.
Agent: claude_code
Execution time: 9713 ms
Cost: $0.27
=> chore: CCIE-4332 use GH_ACTIONS_HELPER_*

templates/templates/.github/workflows/fogg_ci.yml.tmpl, testdata/github_actions/.github/workflows/fogg_ci.yml, testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
This is an AI generated PR.
Agent: claude_code
Execution time: 107406 ms
Cost: $0.41
=> chore: upgrade actions/cache to v4
