- apply/apply.go
- templates/account/Makefile.tmpl
- templates/component/Makefile.tmpl
- templates/global/Makefile.tmpl
- templates/module/Makefile.tmpl
- templates/repo/Makefile.tmpl
After this we will no longer chmod files to be executable. The scripts that need to be
can be run with 'sh'.
I tested this on shared-infra and it appears to work fine with `make docs`.
fixes #77
> fix file modes

- templates/account/Makefile.tmpl
- templates/component/Makefile.tmpl
- templates/global/Makefile.tmpl
- templates/module/Makefile.tmpl
Salient issue is that certain files (such as the plugin cache directory) are owned by root in the host filesystem. 
This PR is intended to work alongside https://github.com/chanzuckerberg/images/pull/21/files
Largely based off https://github.com/broadinstitute/viral-ngs-deploy/tree/951a1f3b68c7901d6a9a835ddaf5eb6c99a20612/docker
> [feature] Don't run tf as root inside the docker container

- plan/plan.go
Now that we have custom providers, we don't have to bundle into image
> [breaking] chanzuckerberg/terraform version 0.2.0

- templates/env/Makefile.tmpl
- templates/module/Makefile.tmpl
- templates/repo/Makefile.tmpl
- templates/repo/scripts/component.mk
This PR removes all the `-it` flags from all docker calls except make apply, effectively removing the TTY allocation.
For the fogg apply, we create a new variable `FOGG_DOCKER_FLAGS` that defaults to blank except in the apply command. We separate apply into apply and real-apply, so that the `-it` flags only apply to the actual `terraform apply` command and not the fmt/get/init/ssh-forward targets, using make's support of [https://www.gnu.org/software/make/manual/html_node/Target_002dspecific.html](target-specific flags)
> Remove TTY from all but fogg apply (closes #127)

- apply/apply.go
- apply/apply_test.go
- cmd/apply.go
- util/version.go
- util/version_test.go
This will check to see if the version in .fogg-version matches the current tool version. If --upgrade/-u is not supplied, apply will fail.
Currently the UX for this error is bad. After the PR I will do a pass at better error UX before we do a release.
Fixes #51
> [feature] check for version mis-match on apply

- templates/repo/scripts/component.mk
I realize I often use fogg run in an interactive mode (e.g. when doing `make run CMD="destroy"`), and the recent change from #127 removed that. This PR restores the TTY to make run. If we have future use cases where we need it disabled, we can see about expanding the Makefile at that point.
> Restore tty to make run

- apply/apply.go
- apply/apply_test.go
- cmd/apply.go
- cmd/plan.go
- plan/plan.go
- plan/plan_test.go
- plan/testdata/full.json
This PR scratches an itch about running fogg while offline or on a slow/expensive connection (e.g. from Caltrain)
It adds a flag to fogg plan and fogg apply, --no-plugins, which skips installing plugins. It's potentially a dangerous command, and it warns you there is danger, if you run terraform apply without having the most recent plugins installed, resulting in either commands failing, or in the worst case wrong behavior if a previously installed plugin had different behavior than the updated version. However, if you know for sure that your plugins are up to date, the flag provides an escape hatch to avoid the slow/expensive download that may not even be possible without Internet access.
It may not be the best way (a better way may be tracking a plugin cache), but wanted to at least …
> Add fogg apply/plan --no-plugins flag

- .travis.yml
This should fail the build if we introduce any insecure dependencies.
> snyk testing

- config/config.go
- plan/plan.go
- plan/travisci.go
- plan/travisci_test.go
- templates/travis-ci/.travis.yml.tmpl
This fixes a problem with the new .travis.yml generation – if the account with the ids (IAM Users) is also an account you are managing, you get duplicate profiles.
> fix .travis.yml when id account is also an account

- apply/apply.go
- apply/apply_test.go
This PR fixes a rare case that happens when initializing a new fogg repo, where an error occurs if a directory does not yet exist when a file is templated. This only happens when the source.Walk inside applyTree happens to pick an order where the first file for the directory happens to be a templated or touched file, before any created or copied files. (From what I can tell, source.Walk walks the files in a random order that changes on each run).
Below is an example of back to back runs on my local machine in an empty directory (except for fogg.json and .git), the first where the error occurs, the 2nd a subsequent run with no filesystem changes in between. Note that the scripts directory does not exist at the start of this.
```
$ fogg apply
INFO scripts/ssh_config templated
ERROR: unable …
```
> Ensure directories are created before template/touch

- .goreleaser.prerelease.yml
- Makefile
- util/version.go
- util/version_test.go
This will allow us to publish to github as a 'pre-release'. Will also skip homebrew.
This is useful for testing changes where you need the new fogg binary in CI.
This also changes the version format for non-release versions to better conform to the semver standard.
> pre-releases

- apply/apply.go
- apply/apply_test.go
This gives fogg the power to create symlinks, driving by our template configurations. Will be used to
link terraform.d directories to a single spot at the repo level.
> [feature] symlinks

- .goreleaser.yml
- Makefile
- apply/apply.go
- apply/apply_test.go
- cmd/apply.go
- cmd/init.go
- cmd/plan.go
- cmd/setup.go
- cmd/util.go
- errs/errs.go
- plan/plan.go
- plan/plan_test.go
- plan/travisci.go
- plan/travisci_test.go
- plugins/constants.go
- plugins/custom_plugin.go
- plugins/custom_plugin_test.go
- setup/setup.go
- templates/account/terraform.d.ln
- templates/component/terraform.d.ln
- templates/global/terraform.d.ln
- templates/repo/.gitignore
- templates/repo/scripts/common.mk
- templates/travis-ci/.travis.yml.tmpl
- util/version_test.go
In order to support running outside of docker containers, we have a new command `fogg setup` which will download and install custom plugins (and anything else we need in the future).
Note that this means "setup the current working copy of this repo" not "setup this repo".
This is a biggish change and includes a few yak-shaves–
1. new command `setup` led to some refactoring  of how we bootstrap the commands. There is probably room to DRY up the other commands, but will leave that to a follow-up.
2. The apply  command no longer does plugins so we no longer need the --no-apply-plugins flag.
3. We now template custom plugins stuff to inject the OS and Arch into them. Example of how to use this is [here](https://github.com/chanzuckerberg/shared-infra/compare/ryanking/symlink-spike?expand=1#diff …
> [feature] [breaking] fogg setup

- .travis.yml
It appears the previous approach doesn't work. I speculate that they don't consider that encrypted env variables are ignored for forks. 🤷‍♂️
> ignore snyk when var not set

- templates/repo/.gitignore
When working on fogg repos, its annoying to continuosly have to close files in my editor before i can easily use git status / git commit commands. This removes that noise.
> ignore vim swap files in .gitignore

- config/config.go
- config/config_test.go
- plan/plan.go
- plan/travisci.go
We defacto require this, since many features will just break if you don't have account ids set.
Fixes #223
> [breaking] require account_id be set in defaults

- apply/apply.go
- cmd/apply.go
- cmd/plan.go
- cmd/setup.go
- cmd/util.go
- plan/plan.go
- plan/plan_test.go
Does not seem to be value in having both, going to just have `--debug/-d`
Fixes #226
> [breaking] consolidate debug and verbose modes

- templates/account/fogg.tf.tmpl
- testdata/snowflake_provider/terraform/accounts/foo/fogg.tf
- testdata/v2_no_aws_provider/terraform/accounts/bar/fogg.tf
- testdata/v2_no_aws_provider/terraform/accounts/foo/fogg.tf
We were using the backend for var.region when it should be the provider region.
* unit tests
Fixes #248
> [fix] region in account fogg.tf

- config/config.go
- config/config_test.go
In preparation for deprecating our docker support, we are defaulting it to off for new repos.
unit tests
* Fixes #259
> default docker to false in init

- .goreleaser.prerelease.yml
- .goreleaser.yml
They changed the format.
- will test the next time we do a release
* https://goreleaser.com/deprecations#archive
> fix goreleaser deprecation warnings

- apply/apply.go
- apply/apply_test.go
- apply/golden_file_test.go
- cmd/setup.go
- cmd/util.go
- config/config.go
- exp/migrate/migrate.go
- main.go
- plan/plan_test.go
- plugins/custom_plugin.go
- setup/setup.go
- util/debugging.go
- util/template.go
Honestly just doing this so that goimports works seamlessly.
* Fixes #256
> switch to using logrus as-is

- apply/apply_test.go
- apply/golden_file_test.go
- cmd/apply.go
- cmd/plan.go
- cmd/util.go
- config/v2/config_test.go
- config/v2/validation.go
- plan/plan_quick_test.go
- plan/plan_test.go
- plan/travisci_test.go
We plan on removing support for running via docker in the future. This PR adds a simple mechanism for displaying warnings and adds one about docker support.
* unit tests
* Fixes #260
> deprecate docker support

- Makefile
We don't do any sort of coordination, goroutines, etc in this project. By removing the race tester, test durations drop from O(seconds) to O(centiseconds) per package. Might as well do this to speed up iteration cycles
unittests
> No race detector for tests

- templates/account/fogg.tf.tmpl
- templates/component/terraform/fogg.tf.tmpl
- templates/global/fogg.tf.tmpl
- testdata/snowflake_provider/terraform/accounts/foo/fogg.tf
- testdata/snowflake_provider/terraform/envs/bar/bam/fogg.tf
- testdata/v1_full/terraform/accounts/bar/fogg.tf
- testdata/v1_full/terraform/accounts/foo/fogg.tf
- testdata/v1_full/terraform/envs/stage/cloud-env/fogg.tf
- testdata/v1_full/terraform/envs/stage/helm/fogg.tf
- testdata/v2_full/terraform/accounts/bar/fogg.tf
- testdata/v2_full/terraform/accounts/foo/fogg.tf
- testdata/v2_full/terraform/envs/staging/comp1/fogg.tf
- testdata/v2_full/terraform/envs/staging/comp2/fogg.tf
- testdata/v2_full/terraform/envs/staging/vpc/fogg.tf
- testdata/v2_no_aws_provider/terraform/accounts/bar/fogg.tf
- testdata/v2_no_aws_provider/terraform/accounts/foo/fogg.tf
- testdata/v2_no_aws_provider/terraform/envs/staging/comp1/fogg.tf
- testdata/v2_no_aws_provider/terraform/envs/staging/comp2/fogg.tf
- testdata/v2_no_aws_provider/terraform/envs/staging/vpc/fogg.tf
For future 0.12 compatibility, this PR modifies fogg to add an equal "`=`" sign between the word `config` and the brace "`{`" inside of `provider` blocks. Hopefully this should be the only change to make fogg generate output that is simultaneously compatible with 0.11 and 0.12. Longer term, there are other changes to make it closer to 0.12 (e.g. some dropping of quotes and "${"), but this should not be needed right now.
Still passes existing tests.
https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks
> Add equal sign after config in providers

- plan/plan.go
- templates/account/fogg.tf.tmpl
- templates/component/terraform/fogg.tf.tmpl
- testdata/v1_full/terraform/accounts/bar/fogg.tf
- testdata/v1_full/terraform/accounts/foo/fogg.tf
- testdata/v1_full/terraform/envs/stage/cloud-env/fogg.tf
- testdata/v1_full/terraform/envs/stage/helm/fogg.tf
- testdata/v2_full/fogg.json
- testdata/v2_full/terraform/envs/staging/comp1/fogg.tf
Changes the generated fogg output to use the top-level defaults when rendering the terraform_remote_state pointing at "global" component, which make sit properly reflect the bucket and path of the global component instead of getting overridden by any account/component level override.
Note that this may have an effect of using the top-level default AWS profile for global instead of any override too. In the particular case of AWS profile, this may not be the desired behavior.
Existing golden file tests were updated to reflect the correct output. A test case was added to the v2_full staging/comp1 component to reflect an override of the profile at the component level.
> Use top-level default settings for global

- .travis.yml
> update travis build to go 1.12

- .travis.yml
I set out to try and find ways to instrument our builds and this is the best option I have found.
This travis build will now use honeycomb's [buildmetrics](https://github.com/honeycombio/buildevents) to trace the build through its execution. We can then analyze the data and alert on any SLIs we care about.
I looked at datadog integration, but their metrics don't include the branch name (because it is high cardinality), so you can't do things like "only alert on master branch failures". Honeycomb, with support for high-cardinality metrics should allow us to do this.
* travis build
* https://github.com/honeycombio/buildevents
> try buildmetrics for tracking builds

- config/config.go
- config/config_test.go
- config/v2/config.go
- config/v2/resolvers.go
- config/v2/resolvers_test.go
- config/v2/validation.go
- plan/plan.go
- plan/plan_test.go
- plan/travisci.go
- plan/travisci_test.go
Before this tools could only be defined at the top level (not per-component).
We would like to be able to configure Atlantis separately for each component. As a bonus this will allow us to do the same for the other tools.
Note that this is a breaking change for config v2, but given that it isn't deployed widely I think we can get away with it.
* unit tests
*
> refactor: move tools to common

- cmd/exp/aws_config.go
- config/config_test.go
- config/v1/config.go
- config/v1/config_test.go
- config/v2/config.go
- config/v2/resolvers.go
- config/v2/validation.go
- plan/plan.go
- plan/plan_test.go
- plan/travisci.go
- plan/travisci_test.go
- util/testing.go
AWS account IDS should be strings (since they can start with 0). We use json.Number (a type alias for string) to allow for backwards compatibility with fogg configs that have ints already.
unittests + apply in existing repos.
> [bug] AWS account IDS should be strings

- templates/atlantis/atlantis.yaml.tmpl
- templates/repo/scripts/common.mk
- templates/repo/scripts/component.mk
- testdata/bless_provider/scripts/common.mk
- testdata/bless_provider/scripts/component.mk
- testdata/okta_provider/scripts/common.mk
- testdata/okta_provider/scripts/component.mk
- testdata/snowflake_provider/scripts/common.mk
- testdata/snowflake_provider/scripts/component.mk
- testdata/v1_full/scripts/common.mk
- testdata/v1_full/scripts/component.mk
- testdata/v2_full/atlantis.yaml
- testdata/v2_full/scripts/common.mk
- testdata/v2_full/scripts/component.mk
- testdata/v2_minimal_valid/scripts/common.mk
- testdata/v2_minimal_valid/scripts/component.mk
- testdata/v2_no_aws_provider/scripts/common.mk
- testdata/v2_no_aws_provider/scripts/component.mk
This configures auto-planning when anything in modules changes. In the future we may want to build a dependency graph between modules and components (including data dependencies), but for now the brute force approach will ensure that we don't miss changes.
* CI
* ran on 1 internal repo
* https://www.runatlantis.io/docs/repo-level-atlantis-yaml.html#configuring-autoplanning
> [fix] atlantis autoplan when modules change

- templates/repo/scripts/component.mk
- testdata/bless_provider/scripts/component.mk
- testdata/okta_provider/scripts/component.mk
- testdata/snowflake_provider/scripts/component.mk
- testdata/v1_full/scripts/component.mk
- testdata/v2_full/scripts/component.mk
- testdata/v2_minimal_valid/scripts/component.mk
- testdata/v2_no_aws_provider/scripts/component.mk
Having `terraform validate` as a substep of `lint` forces us to have fully configured providers (including credentials/secrets). I would like to be able to lint code without requiring these secrets be present. One way could be moving this validation over to the plan stage (although this feels somewhat redundant).
> [feature] Move terraform validate from lint stage to plan stage

- .travis.yml
https://github.com/honeycombio/buildevents/pull/24/files was a breaking change to how buildevents artifacts are released
unittests
> [fix] buildevents is now published at a different location

- templates/repo/scripts/common.mk
- templates/repo/scripts/component.mk
- testdata/bless_provider/scripts/common.mk
- testdata/bless_provider/scripts/component.mk
- testdata/okta_provider/scripts/common.mk
- testdata/okta_provider/scripts/component.mk
- testdata/snowflake_provider/scripts/common.mk
- testdata/snowflake_provider/scripts/component.mk
- testdata/v1_full/scripts/common.mk
- testdata/v1_full/scripts/component.mk
- testdata/v2_full/scripts/common.mk
- testdata/v2_full/scripts/component.mk
- testdata/v2_minimal_valid/scripts/common.mk
- testdata/v2_minimal_valid/scripts/component.mk
- testdata/v2_no_aws_provider/scripts/common.mk
- testdata/v2_no_aws_provider/scripts/component.mk
Fixes https://github.com/chanzuckerberg/fogg/issues/310. This turns off refresh for plan/apply. This gives us quicker plan/apply at the expense of some correctness checks.  
unittests + apply in repos
- https://www.terraform.io/docs/commands/refresh.html
- https://www.terraform.io/docs/commands/plan.html#refresh-true
> [feature] Optionally turn off refresh for plan/apply using REFRESH_ENABLED

- Makefile
The go git library does not respect nested .gitignores. Having this bin/bff is somewhat annoying at the time of release. Instead just read bff from PATH.
> [fix] Read the system bff, and not a local path to bin/bff

- exp/examine/examine.go
- exp/examine/latest.go
- exp/examine/latest_test.go
- exp/examine/local.go
- util/module_storage.go
Replaces uses of the internal function inside Terraform for parsing modules with a more supported separate library hashicorp/terraform-config-inspect. This library also provides support for properly parsing Terraform 0.12 HCL2 syntax. Mostly a drop in replacement, although I renamed some variables to match the new type names of the library.
> Use terraform-config-inspect module, add TF 0.12 input syntax support

- templates/repo/Makefile.tmpl
- templates/travis-ci/.travis.yml.tmpl
- testdata/bless_provider/Makefile
- testdata/github_provider/Makefile
- testdata/okta_provider/Makefile
- testdata/snowflake_provider/Makefile
- testdata/v1_full/.travis.yml
- testdata/v1_full/Makefile
- testdata/v2_full/Makefile
- testdata/v2_minimal_valid/Makefile
- testdata/v2_no_aws_provider/Makefile
- testdata/version_detection/Makefile
Fixes the issue where the fogg apply before the git --porcelain check is unable to find the fogg that was downloaded by make setup.
> [fix] hard code path to fogg in Makefile and .travis.yml

- .goreleaser.yml
The most recent release of fogg showed a deprecation warning pointing at https://goreleaser.com/deprecations/#brew for the Goreleaser run. This PR addresses the deprecation.
> Update goreleaser.yml to use brews

- templates/repo/scripts/component.mk
- testdata/bless_provider/scripts/component.mk
- testdata/github_provider/scripts/component.mk
- testdata/okta_provider/scripts/component.mk
- testdata/snowflake_provider/scripts/component.mk
- testdata/v1_full/scripts/component.mk
- testdata/v2_full/scripts/component.mk
- testdata/v2_minimal_valid/scripts/component.mk
- testdata/v2_no_aws_provider/scripts/component.mk
We've been having trouble in CI due to check-plans failing to acquire locks. Since these ops are readonly, ignoring the lock seems to be an ok compromise and not introduce any undue risk.
> [feature] Do not lock statefile during a check-plan (readonly)

- templates/repo/Makefile.tmpl
- testdata/bless_provider/Makefile
- testdata/github_provider/Makefile
- testdata/okta_provider/Makefile
- testdata/snowflake_provider/Makefile
- testdata/v1_full/Makefile
- testdata/v2_full/Makefile
- testdata/v2_minimal_valid/Makefile
- testdata/v2_no_aws_provider/Makefile
I am somewhat surprised that this hasn't been causing us trouble.
* unit tests
> [fix] ensure we always download the right version of fogg

- templates/repo/scripts/common.mk
- templates/repo/scripts/component.mk
- testdata/bless_provider/scripts/common.mk
- testdata/bless_provider/scripts/component.mk
- testdata/github_provider/scripts/common.mk
- testdata/github_provider/scripts/component.mk
- testdata/okta_provider/scripts/common.mk
- testdata/okta_provider/scripts/component.mk
- testdata/snowflake_provider/scripts/common.mk
- testdata/snowflake_provider/scripts/component.mk
- testdata/v1_full/scripts/common.mk
- testdata/v1_full/scripts/component.mk
- testdata/v2_full/scripts/common.mk
- testdata/v2_full/scripts/component.mk
- testdata/v2_minimal_valid/scripts/common.mk
- testdata/v2_minimal_valid/scripts/component.mk
- testdata/v2_no_aws_provider/scripts/common.mk
- testdata/v2_no_aws_provider/scripts/component.mk
Previously `terraform fmt` would always recurse into nested directories,
including .terraform. This caused two problems–
1. `terraform fmt` would try to reformat modules which had been init'ed.
Beacause these modules are just git checkouts later updates to those
modules would fail due to uncommited changes in those working dirs.
2. `terraform fmt -check`, run via `make lint` would fail if modules in-updates
had format errors.
To work around this, we did a non-recursive list of terraform files and
called `terraform fmt` for each one, which is somewhat slower.
Now `terraform fmt` *does not* recurse by default, so we can remove our
workaround. …
> simplify `make fmt`

- templates/env/Makefile.tmpl
- templates/repo/scripts/common.mk
- testdata/bless_provider/scripts/common.mk
- testdata/bless_provider/terraform/envs/bar/Makefile
- testdata/github_provider/scripts/common.mk
- testdata/github_provider/terraform/envs/bar/Makefile
- testdata/okta_provider/scripts/common.mk
- testdata/okta_provider/terraform/envs/bar/Makefile
- testdata/snowflake_provider/scripts/common.mk
- testdata/snowflake_provider/terraform/envs/bar/Makefile
- testdata/v1_full/scripts/common.mk
- testdata/v1_full/terraform/envs/stage/Makefile
- testdata/v2_full/scripts/common.mk
- testdata/v2_full/terraform/envs/prod/Makefile
- testdata/v2_full/terraform/envs/staging/Makefile
- testdata/v2_minimal_valid/scripts/common.mk
- testdata/v2_no_aws_provider/scripts/common.mk
- testdata/v2_no_aws_provider/terraform/envs/prod/Makefile
- testdata/v2_no_aws_provider/terraform/envs/staging/Makefile
Two small changes to clean up the output when running make targets.
1. When commands across a bunch of components at once, it helps to print
out the component name before we run each one.
2. suppress the command output for the `tfenv install`
* unit tests
> output component name & suppress tfenv command

- cmd/exp/aws_config.go
botocore will consume both stderr and stdout for their cred_process. We use this hack to make sure that stderr is displayed back to the user. stdout is still consumed by botocore as normal.
```
aws sts get-caller-identity --profile XXXXXX
INFO[0001] Requesting MFA. Please complete two-factor authentication with your second device             
INFO[0002] Device: XXXXXXX                               
{
"Account": "XXXXXXXX", 
"UserId": "XXXXXX", 
"Arn": "arn:aws:sts::XXXX:assumed-role/XXXX/XXXX"
}
```
https://github.com/boto/botocore/issues/1348
> [feature] aws cred_process redirects stderr to /dev/tty such that users can see mfa prompts

- templates/account/Makefile.tmpl
- templates/global/Makefile.tmpl
- testdata/bless_provider/terraform/accounts/foo/Makefile
- testdata/bless_provider/terraform/global/Makefile
- testdata/github_provider/terraform/accounts/foo/Makefile
- testdata/github_provider/terraform/global/Makefile
- testdata/okta_provider/terraform/accounts/foo/Makefile
- testdata/okta_provider/terraform/global/Makefile
- testdata/snowflake_provider/terraform/accounts/foo/Makefile
- testdata/snowflake_provider/terraform/global/Makefile
- testdata/v1_full/terraform/accounts/bar/Makefile
- testdata/v1_full/terraform/accounts/foo/Makefile
- testdata/v1_full/terraform/global/Makefile
- testdata/v2_full/terraform/accounts/bar/Makefile
- testdata/v2_full/terraform/accounts/foo/Makefile
- testdata/v2_full/terraform/global/Makefile
- testdata/v2_minimal_valid/terraform/global/Makefile
- testdata/v2_no_aws_provider/terraform/accounts/bar/Makefile
- testdata/v2_no_aws_provider/terraform/accounts/foo/Makefile
- testdata/v2_no_aws_provider/terraform/global/Makefile
When intially built in b93a1d6d3f5b6a2395015b7fe2de4126415f1481, I
missed setting `HEROKU_PROVIDER` in accounts and global, which meant
that the heroku auth checks did not get run.
* travis-ci tests
*
> [fix] triggering heroku auth checks

- .travis.yml
- templates/travis-ci/.travis.yml.tmpl
- testdata/v1_full/.travis.yml
sudo keyword is fully deprecated in travis CI.  made changes to remove it from the travis configuration file.
ran make test locally
> [fix] remove deprecated sudo command from travis configuartion

- apply/apply_test.go
- apply/golden_file_test.go
- config/config_test.go
- config/v2/config_test.go
- config/v2/resolvers_test.go
- config/v2/validation_test.go
- init/init_test.go
- plan/ci_test.go
- plan/plan_test.go
- plugins/custom_plugin_test.go
- util/module_storage_test.go
- util/version_test.go
We have been slowly doing this, but that has been creating a fair amount
of confusion.
We prefer require over assert because assert does not stop when it
fails, while require does. I have found that this is what people expect
from testing assertions.
* ci
* https://godoc.org/github.com/stretchr/testify/assert
* https://godoc.org/github.com/stretchr/testify/require
> [testing] replace assert with require

- cmd/root.go
This enables running cpu profiles and writing them to disk. They can be analyzed with [standard go tools](https://blog.golang.org/pprof)
* CI
* https://blog.golang.org/pprof
> [feature] add ability to run a cpu profile

- config/v2/resolvers.go
- plan/ci.go
Couple of issues.
1. provider CI values are not parsed so we always use default values.
2. When default value for CI provider aws is disabled, we are resetting all the providers.
Ran the following tests locally.
1. set default to (disabled:true) and none of accounts/envs are configured - Made sure we don't generate CI config for all of them.
2. set default to (disabled:false) and none of accounts/envs are configured - Made sure we do generate CI config for all of them.
3. set default to (disabled:true) and only 1 account has disabled:false - Made sure only that account has config generated.
4. Did the above test for env.
5. Verified by not configuring default values and account/env values takes precedence.
> [fix] CI provider aws value configuration

- .goreleaser.prerelease.yml
- .goreleaser.yml
No one has ever downloaded any fogg docker image from GitHub registry. Might as well get rid of them and speed up our builds.
> [feature] Disable Docker releases

- config/v2/config.go
- testdata/bless_provider_yaml/fogg.yml
- testdata/snowflake_provider_yaml/fogg.yml
This change will cause fogg to throw an error whenever it encounters an
unknown field in the yaml configuration.
* CI
* https://godoc.org/gopkg.in/yaml.v3#Decoder.KnownFields
> [fix] error when we encounter an unknown field

- plan/plan.go
- templates/account/fogg.tf.tmpl
- templates/common/aws_provider.tmpl
- templates/component/terraform/fogg.tf.tmpl
- templates/global/fogg.tf.tmpl
- testdata/v2_full_yaml/fogg.yml
- testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf
- testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/datadog/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/hero/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp1/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp2/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/vpc/fogg.tf
- testdata/v2_full_yaml/terraform/global/fogg.tf
Refactor our aws provider configurations in to a common template that is shared across global, accounts and components.
Also push the logic for generating per-region providers from the templates to the planning stage.
> [refactor] aws provider into common template

- plan/plan.go
- plan/plan_test.go
- templates/repo/.terraformignore.tmpl
- testdata/bless_provider_yaml/.terraformignore
- testdata/circleci/.terraformignore
- testdata/github_actions/.terraformignore
- testdata/github_provider_yaml/.terraformignore
- testdata/okta_provider_yaml/.terraformignore
- testdata/snowflake_provider_yaml/.terraformignore
- testdata/tfe_provider_yaml/.terraformignore
- testdata/v2_full_yaml/.terraformignore
- testdata/v2_minimal_valid_yaml/.terraformignore
- testdata/v2_no_aws_provider_yaml/.terraformignore
Make the configuration simpler and 10x faster at building slugs.
This is faster because the process seems to be CPU bound when you have a
large number of patterns in your .terraformignore.
And slug sizes are smaller because we now exclude modules directorties.
Tested on shared-infra and runtime when from 6m -> 12s and slug size
from 75MB to 5MB.
* library that builds the slugs - https://github.com/hashicorp/go-slug
> [fix] simplify and optimize .terraformignore

- config/v2/config.go
- config/v2/resolvers.go
- plan/plan.go
- templates/common/okta_provider.tmpl
- testdata/okta_provider_yaml/fogg.yml
- testdata/okta_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/okta_provider_yaml/terraform/envs/bar/bam/fogg.tf
- testdata/okta_provider_yaml/terraform/global/fogg.tf
Allow users to optionally specify [base_url](https://www.terraform.io/docs/providers/okta/index.html#base_url) for okta provider. For example, if you have an oktapreview instance you want to write some test code against. 
unit tests
https://www.terraform.io/docs/providers/okta/index.html#base_url
> [feature] Okta Provider: Allow specifying base url

- templates/account/fogg.tf.tmpl
- testdata/bless_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/github_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/okta_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/snowflake_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/tfe_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf
- testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
Adds tags variable to accounts components, with standard names for project, env (hardcoded to "accounts") and service (matches the account name). Makes it simpler for adding tags to components such as IAM users that are created in an account component.
Golden files updated.
> Add standard tags to accounts components

- config/v2/config.go
- config/v2/resolvers.go
- config/v2/validation.go
- plan/plan.go
- templates/common/bless_provider.tmpl
- testdata/bless_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/bless_provider_yaml/terraform/envs/bar/bam/fogg.tf
- testdata/bless_provider_yaml/terraform/global/fogg.tf
- testdata/v2_full_yaml/fogg.yml
- testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf
- testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
Allow configuring bless providers with a role_arn, in addition to a profile.
Support was
[previously](https://github.com/chanzuckerberg/terraform-provider-bless/pull/33)
added to the provider.
* unit tests
* https://github.com/chanzuckerberg/terraform-provider-bless/pull/33
> [feature] configure bless providers with a role

- exp/state/remote_state.go
Experimental code, so not well tested. Turns out there was a typo.
* manually tested in one repo
> [fix] typo in experimental auto-remote-state code

- .github/workflows/build.yml
Remove the disabled set-env directives. See [the github
blog](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for more info.
* https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> [fix] remove deprecated set-env

- .golangci.yml
- cmd/exp.go
- cmd/exp_auto_remote_state.go
- cmd/exp_aws_config.go
- cmd/exp_entropy.go
- cmd/exp_examine.go
- cmd/exp_migrate.go
- cmd/root.go
Flatten cmd/exp into cmd, prefixing each file with exp_. This should
make it easier to DRY up some code in these two packages.
* ci
> [refactor] flatten cmd/exp package into cmd

- config/v2/config.go
- exp/state/remote_state.go
Do not ignore empty lists in the `exp auto-remote-state` command.
Without this change an empty list would not get written to fogg.yml,
meaning that components with zero remote state dependencies would not
get updated.
* ci
* tested manually on 1 internal repo
> [fix] exp auto-remote-state to handle empty lists correctly

- cmd/fmt.go
- cmd/plan.go
- config/v2/config.go
- templates/repo/Makefile.tmpl
- testdata/bless_provider_yaml/Makefile
- testdata/circleci/Makefile
- testdata/github_actions/Makefile
- testdata/github_provider_yaml/Makefile
- testdata/okta_provider_yaml/Makefile
- testdata/snowflake_provider_yaml/Makefile
- testdata/tfe_provider_yaml/Makefile
- testdata/v2_full_yaml/Makefile
- testdata/v2_minimal_valid_yaml/Makefile
- testdata/v2_no_aws_provider_yaml/Makefile
Add `fogg fmt` command which implements a standard formatting for the fogg.yml file (shared with other commands which update fogg.yml.
Various scripts, code editors and tools format yaml files differently, leading to diffs with a lot of noise. This command will help enforce a standardized format.
* manually tested on all internal repos
*
> [feature] fogg fmt - standard formatting for fogg.yml

- exp/modules/modules.go
For use in TFE trigger prefixes, these need to be relative to the
repository root.
* https://www.terraform.io/docs/cloud/api/workspaces.html
> [fix] module map relative to repository root

- .goreleaser.yml
https://goreleaser.com/deprecations/#brewsgithub
> fix:goreleaser: brews.github deprecated in favor of brews.tap

- .github/workflows/codeql-analysis.yml
Fix based on a warning from [this build](https://github.com/chanzuckerberg/go-misc/runs/2238808342?check_suite_focus=true):
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
> [fix] Remove git checkout HEAD^2  in CodeQL initialization process

- templates/templates/.github/workflows/fogg_ci.yml.tmpl
- testdata/github_actions/.github/workflows/fogg_ci.yml
- testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
I noticed that a lot of the PRs for fogg related repos were throwing this error: 
~~~
Run cd terraform/modules/aws-iam-eks-pod-role
Terraform v0.13.5 is already installed
fmt: 
/home/runner/work/shared-infra/shared-infra/scripts/update-readme.sh: line 12: terraform-docs: command not found
Docs are out of date, run `make docs`
~~~
[Here](https://github.com/chanzuckerberg/shared-infra/runs/3146638646?check_suite_focus=true#step:195:1) is an example.
This PR should fix this by installing `terraform-docs` in the Github Action template and add the binary to the `$GITHUB_PATH` variable.
* Pull new version of fogg
* Create a fogg repo or use an existing fogg repo
* Make README that needs formatting
* Push a PR for that README
* Verify the error is no longer there.
> feat[terraform-docs]: installing terraform-docs

- apply/apply.go
Whenever fogg apply is run, the entire output looks like something like:
~~~
...
INFO terraform/modules/domain-redirect/outputs.tf skipped touch 
INFO terraform/modules/domain-redirect/variables.tf skipped touch
INFO terraform/modules/netvr-server/README.md skipped 
INFO terraform/modules/netvr-server/fogg.tf templated 
INFO terraform/modules/netvr-server/main.tf skipped touch 
INFO terraform/modules/netvr-server/outputs.tf skipped touch 
INFO terraform/modules/netvr-server/variables.tf skipped touch 
...
~~~
Which isn't very helpful. It makes it difficult to see what actually was changed. This PR makes the "skipped touch" log line a debug level so it doesn't bog down the normal standard output of the tool, but is visible when needed for debugging.
> fix[trace]: making a skipped touch a trace log

- templates/templates/common/backends.tmpl
- testdata/remote_backend_yaml/terraform/accounts/acct1/fogg.tf
- testdata/remote_backend_yaml/terraform/global/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp1/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp2/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/vpc/fogg.tf
Backend workspaces should be a block not an argument. https://www.terraform.io/language/settings/backends/configuration
golden files updated
https://www.terraform.io/language/settings/backends/configuration
> fix: Backend Workspaces is a block, not argument

- download.sh
We release tars for darwin-arm64 architectures, however the download.sh script does not have this hardcoded.
Confirmed that this works via command line on a Darwin-ARM64 device.
> chore: Add darwin/arm64 to downloadable architectures

- templates/templates/component/terraform/fogg.tf.tmpl
- testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
- testdata/v2_full_yaml/fogg.yml
- testdata/v2_full_yaml/terraform/accounts/bar/Makefile
- testdata/v2_full_yaml/terraform/accounts/bar/fogg.tf
- testdata/v2_full_yaml/terraform/accounts/foo/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/datadog/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/hero/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/okta/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/sentry/fogg.tf
- testdata/v2_full_yaml/terraform/envs/prod/vpc/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp1/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/comp2/fogg.tf
- testdata/v2_full_yaml/terraform/envs/staging/vpc/fogg.tf
- testdata/v2_full_yaml/terraform/global/fogg.tf
This PR fixes a bug in that AWS account IDs were being templated as numbers. This is a problem when AWS account IDs start with zeroes because terraform will cast them to string without the leading zeros. For instance, `0000000000000009273135997` will be transformed to `"9273135997"`.
* make update-golden-files
* make test
* [failed terraform plan](https://si.prod.tfe.czi.technology/app/shared-infra/workspaces/accounts-czi-id/runs/run-D1ndxWxfEBU3V5uq)
> fix: treat AWS account IDs as strings

- templates/templates/repo/.gitattributes
- testdata/auth0_provider_yaml/.gitattributes
- testdata/bless_provider_yaml/.gitattributes
- testdata/circleci/.gitattributes
- testdata/github_actions/.gitattributes
- testdata/github_provider_yaml/.gitattributes
- testdata/okta_provider_yaml/.gitattributes
- testdata/remote_backend_yaml/.gitattributes
- testdata/snowflake_provider_yaml/.gitattributes
- testdata/tfe_provider_yaml/.gitattributes
- testdata/v2_full_yaml/.gitattributes
- testdata/v2_minimal_valid_yaml/.gitattributes
- testdata/v2_no_aws_provider_yaml/.gitattributes
The new fogg verision introduces a `fogg_ci.yml` for Github Actions. Adding new components to fogg also introduces changes to that file, similar to `fogg.tf`. Given that it's all auto generated, we can mark the file as such so its hidden during PR review. 
Updated existing tests, tests should pass.
> chore: mark fogg_ci.yml as auto generated

- plan/plan.go
- testdata/snowflake_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/snowflake_provider_yaml/terraform/envs/bar/bam/fogg.tf
- testdata/snowflake_provider_yaml/terraform/global/fogg.tf
In transitioning support of the Snowflake Terraform provider to Snowflake, the hardcoded organization needed to be replaced.
```
make update-golden-files
go get -u ./...
make test
go run main.go
go mod tidy
```
[ONCALL-56]
[ONCALL-56]: https://czi-eng.atlassian.net/browse/ONCALL-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat!: Use Snowflake-Lab version of Terraform Snowflake provider

- templates/templates/repo/.gitignore
- testdata/auth0_provider_yaml/.gitignore
- testdata/bless_provider_yaml/.gitignore
- testdata/circleci/.gitignore
- testdata/github_actions/.gitignore
- testdata/github_provider_yaml/.gitignore
- testdata/okta_provider_yaml/.gitignore
- testdata/remote_backend_yaml/.gitignore
- testdata/snowflake_provider_yaml/.gitignore
- testdata/tfe_provider_yaml/.gitignore
- testdata/v2_full_yaml/.gitignore
- testdata/v2_minimal_valid_yaml/.gitignore
- testdata/v2_no_aws_provider_yaml/.gitignore
`.terraform.lock.hcl` files are created locally whenever a user needs to manage TFE state. These should not be pushed so the state isn't locked inadvertently.
```
make update-golden-files
make test
```
[ONCALL-60]
[ONCALL-60]: https://czi-eng.atlassian.net/browse/ONCALL-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Have Git ignore .terraform.lock.hcl

- plan/plan.go
Bump `databricks` provider from `databrickslabs/databricks` to `databricks/databricks`, given that the provider is being moved: https://github.com/databricks/terraform-provider-databricks/blob/master/CHANGELOG.md
Ran `make update-golden-files` successfully
> feat: CDI-199 Change databricks provider source to databricks/databricks

- util/module_storage.go
- util/module_storage_test.go
This PR allows Github Actions utilize installation tokens as an authentication mechanism as opposed to SSH keys.
Unittests
* https://github.com/tibdex/github-app-token
> feat: allowing fogg to run with a github app token

- util/module_storage.go
- util/module_storage_test.go
This PR fixes an issue where the cache was breaking when using Github App credentials because Github App credentials are 1 time use and each time we'd call fogg with the credentials, the full source URL would be different. To solve this, we change the user and password field of the URL to REDACTED:REDACTED so the URL for the same source will be the same.
Unittests
> fix: cache breaking with github app creds

- cmd/init.go
- init/init.go
> feat: CCIE-180 allow running 'fogg init' with flags instead of realtime user prompts

- cmd/init.go
- config/config.go
- config/config_test.go
- init/init.go
- init/init_test.go
> fix: Prevent including table if its an empty string

- cmd/init.go
Changes some arbitrary stuff to re-trigger release please because it glitched and failed to release the last version
> fix: bump failed release

- apply/apply.go
- apply/apply_test.go
This PR uses the default version from the fogg.yml file when selecting the version to use in the TFE workspace. 
> fix: issue where the default version is not used

- apply/apply.go
We want the default remote apply behavior to be true so that all plans/applies happen on TFE and not locally.
> fix: remote apply default true

- templates/templates/.github/workflows/fogg_ci.yml.tmpl
- testdata/github_actions/.github/workflows/fogg_ci.yml
- testdata/v2_full_yaml/.github/workflows/fogg_ci.yml
This PR fixes a bug where modules have next folders failing CICD checks.
> fix: don't list nested dirs in modules folders ci

- config/v2/config.go
- config/v2/resolvers.go
- plan/plan.go
- testdata/auth0_provider_yaml/fogg.yml
- testdata/auth0_provider_yaml/terraform/accounts/foo/fogg.tf
- testdata/auth0_provider_yaml/terraform/envs/bar/bam/fogg.tf
- testdata/auth0_provider_yaml/terraform/global/fogg.tf
This PR makes the auth0 provider configurable so that the user can change the host based on their provider version. This should allow you to do something like:
~~~
dev:
providers:
auth0:
version: 0.37.1   
source: "auth0/auth0". 
domain: mydomain.com
~~~
* auth0_config testdata section
> feat: make auth0 provider configurable

- cmd/exp_examine.go
- cmd/init.go
- config/config.go
- config/config_test.go
- exp/examine/examine.go
- exp/examine/latest.go
- exp/examine/local.go
- exp/examine/local_test.go
- exp/examine/util.go
- init/init.go
- init/init_test.go
- migrations/migrations.go
Fogg requires the AWS Provider's AccountID to be set in the default configuration. The `fogg init` interview does not ask for this account ID, so the `fogg.yml` file produced is immediately invalid. Users trying to create a new fogg project are greeted with an error when running any subsequent command.
This PR adds AWS Account ID to the interview for the initial `fogg.yml` file so fogg subsequently works properly.
> fix: Add AWS Account ID to fogg init interview

- config/v2/resolvers.go
This commit fixes a few instances where the function named in the comment didn't match its definition.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!
> fix: Fix small typos in function comments

- apply/apply.go
- templates/templates/module-invocation/main.tf.tmpl
- testdata/tfe_config/fogg.yml
- testdata/tfe_config/terraform/tfe/main.tf
This PR allows users to be able to change the default "locals.*" variable to something that is known ahead of time. This is handy when we want to code generate infra stacks that are very similar and we know most of the values ahead of time. Also, filters out non-existent variables on the module source. Fixes https://github.com/chanzuckerberg/fogg/issues/935
Example: 
~~~
module_source:  github.com/chanzuckerberg/cztack//aws-aurora-postgres?ref=main
variables: 
- env=var.tags.env
- owner=var.tags.owner
- project
- blah # will be filtered out
~~~
Would generate:
~~~tf
module "aws-aurora-postgres" {
source                = "github.com/chanzuckerberg/cztack//aws-aurora-postgres?ref=main"
database_name         = local.database_name
database_password     = local.database_password …
> feat: allow variables to specify values in main.tf

- .github/workflows/conventional_commits_title.yml
- .github/workflows/dependabot_automerge.yml
- .github/workflows/release.yml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
> fix: Update runs-on labels in GitHub Actions workflows

- SECURITY.md
- apply/apply.go
Fogg reverts any admin privilege grants to a tfe team currently: https://github.com/chanzuckerberg/shared-infra/pull/11302/commits/da3f2aa45bde3100a21439915e7250ff12bf92bc
> feat: CDI-4361 - Allow for admin teamprivilege type for TFE workspace
